import type { Metadata } from "next";
import "./globals.css";
import { Inter, Manrope } from "next/font/google";

import Button from '@/components/button';
import Card from '@/components/card';
import Header from '@/src/app/header';
/*import Footer from '@/src/app/footer';*/

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-body",
});

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-title",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${manrope.variable} antialiased text-xs sm:text-xs md:text-sm lg:text-base leading-relaxed`}>
        <Header />
        {children}

        <div className="space-y-4 p-6">
          <Button loading>Loading...</Button>

          <Card
            title="Card dengan tombol"
            description="Contoh card dengan elemen tambahan."
            className="bg-[var(--utility-translucent)]"
          >
            <Button className="bg-[var(--foreground)] text-[var(--utility)]">Default</Button>
          </Card>
        </div>

      </body>
    </html>
  );
}
